AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda for creating handle for a URI

Parameters:
  CognitoAuthorizerArn:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: Reference to Cognito UserPool for the stage
    Default: CognitoAuthorizerArn
  CognitoAuthorizerUrls:
    Type: AWS::SSM::Parameter::Value<CommaDelimitedList>
    Default: CognitoAuthorizerUrls
  ExternalCognitoAuthorizerArn:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: Reference to ARN of ExternalUsers UserPool
    Default: ExternalCognitoAuthorizerArn
  ApiDomain:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: The Api domain
    Default: /NVA/ApiDomain
  CustomDomainBasePath:
    Type: String
    Description: Base path mapping in CustomDomain
    Default: handle
  ApprovalsDomainBasePath:
    Type: String
    Default: approval
  HandleBaseUri:
    Type: String
    Description: The host part of Handle URIs
    Default: https://hdl.handle.net
  HandlePrefix:
    Type: String
    Description: Reference to Handle Prefix to use
    Default: 11250.1
  HandlePrefixForApprovals:
    Type: String
    Description: Reference to Handle Prefix to use when creating approvals
    Default: 20.500.14886
  HandleDatabaseSecretName:
    Type: String
    Default: HandleDatabase
  EIPPrivateSubnet:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: Private Subnet ID for workloads where we need a static IP
    Default: /NVA/EIP/PrivateSubnet/id
  EIPSecurityGroupId:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: Security Group ID for workloads where we need a static IP
    Default: /NVA/EIP/SecurityGroup/GroupId
  AllowedOrigins:
    Type: String
    Description: comma separated list of external clients that are allowed to contact the HTTP APIs, "*" indicates that all origins are allowed
    Default: '*'
  DmpClientSecretName:
    Type: String
    Description: Name of the secret containing DMP API client credentials
    Default: DmpClientCredentials

Conditions:
  IsProd: !Equals [!Ref ApiDomain, 'api.nva.unit.no']

Globals:
  Function:
    Timeout: 900
    MemorySize: 1798
    Runtime: java21
    Architectures:
      - arm64
    Environment:
      Variables:
        ALLOWED_ORIGIN: !Ref AllowedOrigins
        API_HOST: !Ref ApiDomain
        COGNITO_AUTHORIZER_URLS: !Join [ ",", !Ref CognitoAuthorizerUrls ]
  Api:
    OpenApiVersion: 3.0.1
    Cors:
      AllowMethods: "'OPTIONS,POST'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Resources:
  ApprovalsTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Delete
    Properties:
      TableName: !Sub nva-approvals-${AWS::StackName}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK0
          AttributeType: S
        - AttributeName: SK0
          AttributeType: S
        - AttributeName: PK1
          AttributeType: S
        - AttributeName: SK1
          AttributeType: S
        - AttributeName: PK2
          AttributeType: S
        - AttributeName: SK2
          AttributeType: S
      KeySchema:
        - AttributeName: PK0
          KeyType: HASH
        - AttributeName: SK0
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: PK1
              KeyType: HASH
            - AttributeName: SK1
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI2
          KeySchema:
            - AttributeName: PK2
              KeyType: HASH
            - AttributeName: SK2
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: IncludedInBackup
          Value: 'true'

  ReadHandleDatabaseSecretsManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource:
              - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:HandleDatabase-*"

  DynamoDbTableAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:BatchGetItem
              - dynamodb:BatchWriteItem
            Resource:
              - !GetAtt ApprovalsTable.Arn
              - !Sub '${ApprovalsTable.Arn}/index/*'

  ReadDmpClientSecretsManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource:
              - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${DmpClientSecretName}-*'

  ApiAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 180

  NvaHandleServiceApi:
    Type: AWS::Serverless::Api
    Properties:
      AccessLogSetting:
        DestinationArn: !GetAtt ApiAccessLogGroup.Arn
        Format: !Join
          - ''
          - - '{ '
            - '"apiId": "$context.apiId", '
            - '"requestId": "$context.requestId", '
            - '"requestTime": "$context.requestTime", '
            - '"requestTimeEpoch": "$context.requestTimeEpoch", '
            - '"httpMethod": "$context.httpMethod", '
            - '"path": "$context.path", '
            - '"queryString": "$context.requestQueryString", '
            - '"status": "$context.status", '
            - '"error.message": "$context.error.message", '
            - '"userAgent": "$context.identity.userAgent", '
            - '"ip": "$context.identity.sourceIp" '
            - '}'
      StageName: Prod
      EndpointConfiguration:
        Type: REGIONAL
      DefinitionBody:
        'Fn::Transform':
          Name: AWS::Include
          Parameters:
            Location: ./docs/handle-openapi.yaml

  NvaApprovalsApi:
    Type: AWS::Serverless::Api
    Properties:
      AccessLogSetting:
        DestinationArn: !GetAtt ApiAccessLogGroup.Arn
        Format: '{ "apiId": "$context.apiId", "requestId": "$context.requestId", "requestTime": "$context.requestTime", "requestTimeEpoch": "$context.requestTimeEpoch", "httpMethod": "$context.httpMethod", "path": "$context.path", "status": "$context.status",  "error.message": "$context.error.message" }'
      StageName: Prod
      EndpointConfiguration:
        Type: REGIONAL
      DefinitionBody:
        'Fn::Transform':
          Name: AWS::Include
          Parameters:
            Location: ./docs/approvals-openapi.yaml

  NvaCreateHandleFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${NvaCreateHandleFunction}
      RetentionInDays: 180

  NvaCreateHandleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: operations
      Handler: no.sikt.nva.handle.CreateHandleHandler::handleRequest
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaVPCAccessExecutionRole
        - !Ref ReadHandleDatabaseSecretsManagedPolicy
      Environment:
        Variables:
          HANDLE_PREFIX: !Ref HandlePrefix
          HANDLE_BASE_URI: !Ref HandleBaseUri
          HANDLE_DATABASE_SECRET_NAME: !Ref HandleDatabaseSecretName
      VpcConfig:
        SecurityGroupIds:
          - !Ref EIPSecurityGroupId
        SubnetIds:
          - !Ref EIPPrivateSubnet
      Events:
        CreateHandle:
          Type: Api
          Properties:
            Path: /
            Method: post
            RestApiId: !Ref NvaHandleServiceApi

  NvaUpdateHandleFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${NvaUpdateHandleFunction}
      RetentionInDays: 180

  NvaUpdateHandleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: operations
      Handler: no.sikt.nva.handle.UpdateHandleHandler::handleRequest
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaVPCAccessExecutionRole
        - !Ref ReadHandleDatabaseSecretsManagedPolicy
      Environment:
        Variables:
          HANDLE_PREFIX: !Ref HandlePrefix
          HANDLE_BASE_URI: !Ref HandleBaseUri
          HANDLE_DATABASE_SECRET_NAME: !Ref HandleDatabaseSecretName
      VpcConfig:
        SecurityGroupIds:
          - !Ref EIPSecurityGroupId
        SubnetIds:
          - !Ref EIPPrivateSubnet
      Events:
        CreateHandle:
          Type: Api
          Properties:
            Path: /{prefix}/{suffix}
            Method: put
            RestApiId: !Ref NvaHandleServiceApi

  NvaCreateApprovalFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${NvaCreateApprovalFunction}'
      RetentionInDays: 90

  NvaCreateApprovalFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: approvals
      Handler: no.sikt.nva.approvals.rest.CreateApprovalHandler::handleRequest
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - !Ref ReadHandleDatabaseSecretsManagedPolicy
        - !Ref DynamoDbTableAccessPolicy
      Environment:
        Variables:
          HANDLE_PREFIX: !If [IsProd, !Ref HandlePrefixForApprovals, !Ref HandlePrefix]
          HANDLE_BASE_URI: !Ref HandleBaseUri
          HANDLE_DATABASE_SECRET_NAME: !Ref HandleDatabaseSecretName
          TABLE: !Ref ApprovalsTable
      VpcConfig:
        SecurityGroupIds:
          - !Ref EIPSecurityGroupId
        SubnetIds:
          - !Ref EIPPrivateSubnet
      Events:
        CreateApproval:
          Type: Api
          Properties:
            Path: /
            Method: post
            RestApiId: !Ref NvaApprovalsApi

  NvaFetchApprovalFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${NvaFetchApprovalFunction}'
      RetentionInDays: 90

  NvaUpdateApprovalFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: approvals
      Handler: no.sikt.nva.approvals.rest.UpdateApprovalHandler::handleRequest
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - !Ref ReadHandleDatabaseSecretsManagedPolicy
        - !Ref DynamoDbTableAccessPolicy
      Environment:
        Variables:
          HANDLE_PREFIX: !If [ IsProd, !Ref HandlePrefixForApprovals, !Ref HandlePrefix ]
          HANDLE_BASE_URI: !Ref HandleBaseUri
          HANDLE_DATABASE_SECRET_NAME: !Ref HandleDatabaseSecretName
          TABLE: !Ref ApprovalsTable
      VpcConfig:
        SecurityGroupIds:
          - !Ref EIPSecurityGroupId
        SubnetIds:
          - !Ref EIPPrivateSubnet
      Events:
        CreateApproval:
          Type: Api
          Properties:
            Path: /{approvalId}
            Method: put
            RestApiId: !Ref NvaApprovalsApi

  NvaUpdateApprovalFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${NvaUpdateApprovalFunction}'
      RetentionInDays: 90

  NvaFetchApprovalFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: approvals
      Handler: no.sikt.nva.approvals.rest.FetchApprovalHandler::handleRequest
      Policies:
        - !Ref DynamoDbTableAccessPolicy
        - !Ref ReadDmpClientSecretsManagedPolicy
      Environment:
        Variables:
          HANDLE_PREFIX: !If [IsProd, !Ref HandlePrefixForApprovals, !Ref HandlePrefix]
          TABLE: !Ref ApprovalsTable
          HANDLE_BASE_URI: !Ref HandleBaseUri
          HANDLE_DATABASE_SECRET_NAME: !Ref HandleDatabaseSecretName
          DMP_CLIENT_SECRET_NAME: !Ref DmpClientSecretName
      Events:
        GetApproval:
          Type: Api
          Properties:
            Path: /{approvalId}
            Method: get
            RestApiId: !Ref NvaApprovalsApi

  NvaFetchContextFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${NvaFetchContextFunction}'
      RetentionInDays: 90

  NvaFetchContextFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: approvals
      Handler: no.sikt.nva.approvals.rest.FetchContextHandler::handleRequest
      Events:
        GetContext:
          Type: Api
          Properties:
            Path: /context
            Method: get
            RestApiId: !Ref NvaApprovalsApi

  NvaFetchOntologyFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${NvaFetchOntologyFunction}'
      RetentionInDays: 90

  NvaFetchOntologyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: approvals
      Handler: no.sikt.nva.approvals.rest.FetchOntologyHandler::handleRequest
      Events:
        GetOntology:
          Type: Api
          Properties:
            Path: /ontology
            Method: get
            RestApiId: !Ref NvaApprovalsApi

  NvaCreateHandleBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: !Sub ${CustomDomainBasePath}
      DomainName: !Ref ApiDomain
      RestApiId: !Ref NvaHandleServiceApi
      Stage: !Ref NvaHandleServiceApi.Stage

  NvaApprovalsApiBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: !Sub ${ApprovalsDomainBasePath}
      DomainName: !Ref ApiDomain
      RestApiId: !Ref NvaApprovalsApi
      Stage: !Ref NvaApprovalsApi.Stage
