package no.sikt.nva.approvals.persistence;

import static no.sikt.nva.approvals.persistence.DynamoDbConstants.GSI1;
import static no.sikt.nva.approvals.persistence.DynamoDbConstants.GSI2;
import static no.sikt.nva.approvals.persistence.DynamoDbConstants.PK0;
import static no.sikt.nva.approvals.persistence.DynamoDbConstants.PK1;
import static no.sikt.nva.approvals.persistence.DynamoDbConstants.PK2;
import static no.sikt.nva.approvals.persistence.DynamoDbConstants.SK0;
import static no.sikt.nva.approvals.persistence.DynamoDbConstants.SK1;
import static no.sikt.nva.approvals.persistence.DynamoDbConstants.SK2;

import java.time.Instant;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbVersionAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSecondaryPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSecondarySortKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSortKey;

public abstract class Dao {

  private String partitionKey0;
  private String sortKey0;
  private String partitionKey1;
  private String sortKey1;
  private String partitionKey2;
  private String sortKey2;

  private String type;
  private Long revision;
  private Instant createdAt;
  private Instant modifiedAt;

  // PK0/SK0 - primary key for lookups by own identifier
  @DynamoDbPartitionKey
  @DynamoDbAttribute(PK0)
  public String getPartitionKey0() {
    return partitionKey0;
  }

  public void setPartitionKey0(String partitionKey0) {
    this.partitionKey0 = partitionKey0;
  }

  @DynamoDbSortKey
  @DynamoDbAttribute(SK0)
  public String getSortKey0() {
    return sortKey0;
  }

  public void setSortKey0(String sortKey0) {
    this.sortKey0 = sortKey0;
  }

  // PK1/SK1 - GSI for lookup by approval identifier
  @DynamoDbSecondaryPartitionKey(indexNames = GSI1)
  @DynamoDbAttribute(PK1)
  public String getPartitionKey1() {
    return partitionKey1;
  }

  public void setPartitionKey1(String partitionKey1) {
    this.partitionKey1 = partitionKey1;
  }

  @DynamoDbSecondarySortKey(indexNames = GSI1)
  @DynamoDbAttribute(SK1)
  public String getSortKey1() {
    return sortKey1;
  }

  public void setSortKey1(String sortKey1) {
    this.sortKey1 = sortKey1;
  }

  // PK2/SK2 - GSI for lookup by handle
  @DynamoDbSecondaryPartitionKey(indexNames = GSI2)
  @DynamoDbAttribute(PK2)
  public String getPartitionKey2() {
    return partitionKey2;
  }

  public void setPartitionKey2(String partitionKey2) {
    this.partitionKey2 = partitionKey2;
  }

  @DynamoDbSecondarySortKey(indexNames = GSI2)
  @DynamoDbAttribute(SK2)
  public String getSortKey2() {
    return sortKey2;
  }

  public void setSortKey2(String sortKey2) {
    this.sortKey2 = sortKey2;
  }

  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  @DynamoDbVersionAttribute
  public Long getRevision() {
    return revision;
  }

  public void setRevision(Long revision) {
    this.revision = revision;
  }

  public Instant getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(Instant createdAt) {
    this.createdAt = createdAt;
  }

  @DynamoDbAutoGeneratedTimestampAttribute
  public Instant getModifiedAt() {
    return modifiedAt;
  }

  public void setModifiedAt(Instant modifiedAt) {
    this.modifiedAt = modifiedAt;
  }
}
