plugins {
    id 'nva-handle-service.java-common-conventions'
}

dependencies {
    api(nvaCatalog.aws.lambda.core)
    api(nvaCatalog.jackson.annotations)
    api(nvaLibs.apigateway)
    api(nvaLibs.core)
    implementation(nvaCatalog.aws.sdk2.secrets)
    implementation(nvaCatalog.log4j.core)
    implementation(nvaCatalog.slf4j.api)
    implementation(nvaLibs.secrets)
    runtimeOnly(libs.postgres)
    testImplementation(nvaCatalog.hamcrest)
    testImplementation(nvaCatalog.jackson.core)
    testImplementation(nvaCatalog.jackson.databind)
    testImplementation(nvaCatalog.junit.jupiter.api)
    testImplementation(nvaCatalog.mockito.core)
    testImplementation(nvaCatalog.zalando)
    testImplementation(nvaLibs.json)
    testImplementation(nvaLibs.logutils)
    testImplementation(nvaLibs.testutils)
}
