package no.sikt.nva.approvals.persistence;

import static no.sikt.nva.approvals.persistence.DynamoDbLocal.dynamoDBLocal;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.net.URI;
import java.time.Instant;
import java.util.UUID;
import nva.commons.core.Environment;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedClient;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbTable;
import software.amazon.awssdk.enhanced.dynamodb.Key;
import software.amazon.awssdk.enhanced.dynamodb.TableSchema;
import software.amazon.awssdk.enhanced.dynamodb.model.QueryConditional;
import software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedTimestampRecordExtension;
import software.amazon.awssdk.enhanced.dynamodb.extensions.VersionedRecordExtension;
import software.amazon.awssdk.services.dynamodb.model.ConditionalCheckFailedException;

public class ExampleTest {

    private static final Environment ENVIRONMENT = new Environment();
    private static final String TABLE = ENVIRONMENT.readEnv(DynamoDbConstants.TABLE);

    private DynamoDbLocal dynamoDbLocal;
    private DynamoDbEnhancedClient enhancedClient;
    private DynamoDbTable<ApprovalDaoV2> approvalTable;
    private DynamoDbTable<HandleDaoV2> handleTable;
    private DynamoDbTable<NamedIdentifierDaoV2> identifierTable;

    @BeforeEach
    void setUp() {
        dynamoDbLocal = dynamoDBLocal(TABLE);
        enhancedClient = DynamoDbEnhancedClient.builder()
            .dynamoDbClient(dynamoDbLocal.client())
            .extensions(
                AutoGeneratedTimestampRecordExtension.create(),
                VersionedRecordExtension.builder().build())
            .build();
        approvalTable = enhancedClient.table(TABLE, TableSchema.fromBean(ApprovalDaoV2.class));
        handleTable = enhancedClient.table(TABLE, TableSchema.fromBean(HandleDaoV2.class));
        identifierTable = enhancedClient.table(TABLE, TableSchema.fromBean(NamedIdentifierDaoV2.class));
    }

    @Test
    void shouldPersistAndReadApprovalDao() {
        var identifier = UUID.randomUUID();
        var sourceUri = URI.create("https://example.org/source/123");

        var approval = createApprovalDao(identifier, sourceUri);
        approvalTable.putItem(approval);

        var key = Key.builder()
            .partitionValue(ApprovalDaoV2.createPartitionKey(identifier.toString()))
            .sortValue(identifier.toString())
            .build();
        var retrieved = approvalTable.getItem(key);

        assertThat(retrieved.getIdentifier()).isEqualTo(identifier);
        assertThat(retrieved.getSourceUri()).isEqualTo(sourceUri);
        assertThat(retrieved.getRevision()).isEqualTo(1L);
        assertThat(retrieved.getModifiedAt()).isNotNull();
    }

    @Test
    void shouldPersistAndReadHandleDao() {
        var handleIdentifier = UUID.randomUUID().toString();
        var handleUri = URI.create("https://hdl.handle.net/11250/123456");

        var handle = createHandleDao(handleIdentifier, handleUri);
        handleTable.putItem(handle);

        var key = Key.builder()
            .partitionValue(HandleDaoV2.createPartitionKey(handleIdentifier))
            .sortValue(handleIdentifier)
            .build();
        var retrieved = handleTable.getItem(key);

        assertThat(retrieved.getHandleUri()).isEqualTo(handleUri);
        assertThat(retrieved.getRevision()).isEqualTo(1L);
        assertThat(retrieved.getModifiedAt()).isNotNull();
    }

    @Test
    void shouldIncrementRevisionOnUpdate() {
        var identifier = UUID.randomUUID();
        var sourceUri = URI.create("https://example.org/source/123");

        var approval = createApprovalDao(identifier, sourceUri);
        approvalTable.putItem(approval);

        var key = Key.builder()
            .partitionValue(ApprovalDaoV2.createPartitionKey(identifier.toString()))
            .sortValue(identifier.toString())
            .build();
        var firstRead = approvalTable.getItem(key);
        assertThat(firstRead.getRevision()).isEqualTo(1L);

        var updatedSourceUri = URI.create("https://example.org/source/456");
        firstRead.setSourceUri(updatedSourceUri);
        approvalTable.putItem(firstRead);

        var secondRead = approvalTable.getItem(key);
        assertThat(secondRead.getRevision()).isEqualTo(2L);
        assertThat(secondRead.getSourceUri()).isEqualTo(updatedSourceUri);
    }

    @Test
    void shouldThrowConditionalCheckFailedExceptionOnOptimisticLockingConflict() {
        var identifier = UUID.randomUUID();
        var sourceUri = URI.create("https://example.org/source/123");

        var approval = createApprovalDao(identifier, sourceUri);
        approvalTable.putItem(approval);

        var key = Key.builder()
            .partitionValue(ApprovalDaoV2.createPartitionKey(identifier.toString()))
            .sortValue(identifier.toString())
            .build();

        var firstRead = approvalTable.getItem(key);
        var secondRead = approvalTable.getItem(key);

        firstRead.setSourceUri(URI.create("https://example.org/updated-by-first"));
        approvalTable.putItem(firstRead);

        secondRead.setSourceUri(URI.create("https://example.org/updated-by-second"));

        assertThatThrownBy(() -> approvalTable.putItem(secondRead))
            .isInstanceOf(ConditionalCheckFailedException.class);
    }

    @Test
    void shouldAllowUpdateAfterRefreshingStaleData() {
        var identifier = UUID.randomUUID();
        var sourceUri = URI.create("https://example.org/source/123");

        var approval = createApprovalDao(identifier, sourceUri);
        approvalTable.putItem(approval);

        var key = Key.builder()
            .partitionValue(ApprovalDaoV2.createPartitionKey(identifier.toString()))
            .sortValue(identifier.toString())
            .build();

        var firstRead = approvalTable.getItem(key);
        var secondRead = approvalTable.getItem(key);

        firstRead.setSourceUri(URI.create("https://example.org/updated-by-first"));
        approvalTable.putItem(firstRead);

        var refreshedData = approvalTable.getItem(key);
        assertThat(refreshedData.getRevision()).isEqualTo(2L);

        refreshedData.setSourceUri(URI.create("https://example.org/updated-after-refresh"));
        approvalTable.putItem(refreshedData);

        var finalRead = approvalTable.getItem(key);
        assertThat(finalRead.getRevision()).isEqualTo(3L);
        assertThat(finalRead.getSourceUri()).isEqualTo(URI.create("https://example.org/updated-after-refresh"));
    }

    @Test
    void shouldDemonstrateOptimisticLockingWithHandleDao() {
        var handleIdentifier = UUID.randomUUID().toString();
        var handleUri = URI.create("https://hdl.handle.net/11250/123456");

        var handle = createHandleDao(handleIdentifier, handleUri);
        handleTable.putItem(handle);

        var key = Key.builder()
            .partitionValue(HandleDaoV2.createPartitionKey(handleIdentifier))
            .sortValue(handleIdentifier)
            .build();

        var firstRead = handleTable.getItem(key);
        var secondRead = handleTable.getItem(key);

        firstRead.setHandleUri(URI.create("https://hdl.handle.net/11250/first-update"));
        handleTable.putItem(firstRead);

        secondRead.setHandleUri(URI.create("https://hdl.handle.net/11250/second-update"));

        assertThatThrownBy(() -> handleTable.putItem(secondRead))
            .isInstanceOf(ConditionalCheckFailedException.class);
    }

    @Test
    void shouldQueryByApprovalIdentifierUsingGsi1() {
        var approvalId = UUID.randomUUID();
        var handleUri = URI.create("https://hdl.handle.net/11250/12345");
        var sourceUri = URI.create("https://example.org/source/abc");

        var approval = ApprovalDaoV2.create(approvalId, handleUri, sourceUri);
        approvalTable.putItem(approval);

        var handle = HandleDaoV2.create(approvalId, handleUri);
        handleTable.putItem(handle);

        var gsi1Index = approvalTable.index(DynamoDbConstants.GSI1);
        var queryResult = gsi1Index.query(r -> r.queryConditional(
            QueryConditional.keyEqualTo(k -> k.partitionValue(ApprovalDaoV2.createPartitionKey(approvalId.toString())))
        ));

        var items = queryResult.stream()
            .flatMap(page -> page.items().stream())
            .toList();

        assertThat(items).hasSize(2);
        assertThat(items).extracting(Dao::getType).containsExactlyInAnyOrder("Approval", "Handle");
    }

    @Test
    void shouldQueryFullAggregateByApprovalIdentifier() {
        var approvalId = UUID.randomUUID();
        var handleUri = URI.create("https://hdl.handle.net/11250/99999");
        var sourceUri = URI.create("https://example.org/source/xyz");

        var approval = ApprovalDaoV2.create(approvalId, handleUri, sourceUri);
        approvalTable.putItem(approval);

        var handle = HandleDaoV2.create(approvalId, handleUri);
        handleTable.putItem(handle);

        var identifier = NamedIdentifierDaoV2.create("doi", "10.1234/example", approvalId, handleUri);
        identifierTable.putItem(identifier);

        var gsi1Index = approvalTable.index(DynamoDbConstants.GSI1);
        var queryResult = gsi1Index.query(r -> r.queryConditional(
            QueryConditional.keyEqualTo(k -> k.partitionValue(ApprovalDaoV2.createPartitionKey(approvalId.toString())))
        ));

        var items = queryResult.stream()
            .flatMap(page -> page.items().stream())
            .toList();

        assertThat(items).hasSize(3);
        assertThat(items).extracting(Dao::getType).containsExactlyInAnyOrder("Approval", "Handle", "Identifier");
    }

    @Test
    void shouldPersistBothTypesAndShowPersistedStructure() {
        var approvalId = UUID.randomUUID();
        var handleUri = URI.create("https://hdl.handle.net/11250/999");
        var sourceUri = URI.create("https://example.org/source/123");

        var approval = ApprovalDaoV2.create(approvalId, handleUri, sourceUri);
        approvalTable.putItem(approval);

        var handle = HandleDaoV2.create(approvalId, handleUri);
        handleTable.putItem(handle);

        var scanResponse = dynamoDbLocal.client().scan(builder -> builder.tableName(TABLE));
        var items = scanResponse.items();

        assertThat(items).hasSize(2);

        System.out.println("\n=== Persisted DynamoDB Items ===\n");
        for (var item : items) {
            System.out.println("Item:");
            item.forEach((key, value) -> System.out.println("  " + key + ": " + value));
            System.out.println();
        }
    }

    private ApprovalDaoV2 createApprovalDao(UUID identifier, URI sourceUri) {
        var approval = new ApprovalDaoV2();
        approval.setIdentifier(identifier);
        approval.setSourceUri(sourceUri);
        approval.setPartitionKey0(ApprovalDaoV2.createPartitionKey(identifier.toString()));
        approval.setSortKey0(identifier.toString());
        approval.setCreatedAt(Instant.now());
        return approval;
    }

    private HandleDaoV2 createHandleDao(String identifier, URI handleUri) {
        var handle = new HandleDaoV2();
        handle.setHandleUri(handleUri);
        handle.setPartitionKey0(HandleDaoV2.createPartitionKey(identifier));
        handle.setSortKey0(identifier);
        handle.setCreatedAt(Instant.now());
        return handle;
    }
}
