openapi: 3.0.1
info:
  title: NVA Handle API
  version: '1.0'
  license:
    name: MIT
paths:
  /:
    post:
      description: Create handle for a URI
      summary: Create handle for a URI. Include prefix and suffix in the body for imported handle or use only uri field for default handle.
      operationId: createHandle
      security:
        - CognitoUserPool: [ 'https://api.nva.unit.no/scopes/backend' ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${NvaCreateHandleFunction.Arn}/invocations
        responses: { }
        httpMethod: POST
        type: AWS_PROXY
      responses:
        '201':
          description: Handle created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        '502':
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
  /{prefix}/{suffix}:
    put:
      description: Update uri for a handle
      summary: Update uri for a handle
      operationId: updateHandle
      parameters:
        - in: path
          name: prefix
          schema:
            type: string
          required: true
          style: simple
          explode: false
          description: The prefix, assigned by a registering organization
        - in: path
          name: suffix
          schema:
            type: string
          required: true
          style: simple
          explode: false
          description: The suffix, a unique identifier for a specific digital object within the namespace of the registering organization.
      security:
        - CognitoUserPool: [ 'https://api.nva.unit.no/scopes/backend' ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${NvaUpdateHandleFunction.Arn}/invocations
        responses: { }
        httpMethod: POST
        type: AWS_PROXY
      responses:
        '200':
          description: Handle updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        '502':
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
components:
  schemas:
    Request:
      type: object
      properties:
        uri:
          type: string
        prefix:
          type: string
        suffix:
          type: string
      required:
        - uri
    Response:
      type: object
      properties:
        handle:
          type: string
      required:
        - handle
    Problem:
      required:
        - detail
        - status
        - title
      type: object
      properties:
        instance:
          type: string
          description: The requested path associated with the error
        requestId:
          type: string
          description: Identifier of the request causing the problem
        detail:
          type: string
          description: A more detailed error message describing the error and potential
            mitigations
        title:
          type: string
          description: Human-readable description of the error status
        type:
          type: string
          description: "A URI describing the error and mitigations, in generic cases,\
            \ this is about:blank"
        status:
          type: integer
          description: The HTTP status code associated with the problem
          format: int32
      description: NVA error reporting object
  securitySchemes:
    CognitoUserPool:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: cognito_user_pools
      x-amazon-apigateway-authorizer:
        type: cognito_user_pools
        providerARNs:
          - Ref:
              CognitoAuthorizerArn